const mongoose = require('mongoose');
const Course = require('../models/Course');
require('dotenv').config({ path: '../.env' });

const MONGO_URI = 'mongodb://localhost:27017/learnspheredb';

const courses = [
    // 15 FREE COURSES
    {
        title: "React Modern Fundamentals",
        description: "Master the basics of React with hooks, functional components, and state management.",
        shortDescription: "Start your journey into modern web development with React.",
        imageUrl: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?auto=format&fit=crop&w=200&q=80",
        category: "Technology",
        tags: ["React", "JavaScript", "Free"],
        price: 0,
        isPaid: false,
        duration: "4 weeks",
        level: "Beginner",
        rating: 4.8,
        reviewsCount: 1250,
        studentsCount: 15400,
        published: true
    },
    {
        title: "JavaScript Mastery",
        description: "Deep dive into ES6+, closures, promises, and async/await.",
        shortDescription: "Become an expert in core JavaScript concepts.",
        imageUrl: "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?auto=format&fit=crop&w=200&q=80",
        category: "Technology",
        tags: ["JavaScript", "ES6", "Free"],
        price: 0,
        isPaid: false,
        duration: "6 weeks",
        level: "Intermediate",
        rating: 4.9,
        reviewsCount: 3400,
        studentsCount: 28000,
        published: true
    },
    {
        title: "Python for Beginners",
        description: "Learn Python from scratch. Cover basic syntax, data types, and loops.",
        shortDescription: "The easiest way to start coding in Python.",
        imageUrl: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=200&q=80",
        category: "Technology",
        tags: ["Python", "Data Science", "Free"],
        price: 0,
        isPaid: false,
        duration: "5 weeks",
        level: "Beginner",
        rating: 4.7,
        reviewsCount: 2100,
        studentsCount: 45000,
        published: true
    },
    {
        title: "HTML & CSS Foundation",
        description: "The building blocks of the web. Learn semantic HTML5 and modern CSS3.",
        shortDescription: "Build beautiful websites using HTML and CSS.",
        imageUrl: "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?auto=format&fit=crop&w=200&q=80",
        category: "Design",
        tags: ["HTML", "CSS", "Free"],
        price: 0,
        isPaid: false,
        duration: "3 weeks",
        level: "Beginner",
        rating: 4.6,
        reviewsCount: 890,
        studentsCount: 12000,
        published: true
    },
    {
        title: "UI/UX Design Principles",
        description: "Learn the core principles of user-centric design and wireframing basics.",
        shortDescription: "Design experiences that users will love.",
        imageUrl: "https://images.unsplash.com/photo-1586717791821-3f44a563eb4c?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1586717791821-3f44a563eb4c?auto=format&fit=crop&w=200&q=80",
        category: "Design",
        tags: ["UI", "UX", "Free"],
        price: 0,
        isPaid: false,
        duration: "4 weeks",
        level: "Beginner",
        rating: 4.8,
        reviewsCount: 1560,
        studentsCount: 19000,
        published: true
    },
    {
        title: "Machine Learning Primer",
        description: "Introduction to supervised learning and Linear Regression.",
        shortDescription: "Demystifying AI and Machine Learning.",
        imageUrl: "https://images.unsplash.com/photo-1555255707-c07966488bd7?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1555255707-c07966488bd7?auto=format&fit=crop&w=200&q=80",
        category: "Data Science",
        tags: ["ML", "AI", "Free"],
        price: 0,
        isPaid: false,
        duration: "6 weeks",
        level: "Intermediate",
        rating: 4.5,
        reviewsCount: 450,
        studentsCount: 8500,
        published: true
    },
    {
        title: "Digital Marketing 101",
        description: "Learn about SEO, SEM, and Social Media Marketing growth.",
        shortDescription: "Master the art of online growth.",
        imageUrl: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&w=200&q=80",
        category: "Marketing",
        tags: ["Marketing", "SEO", "Free"],
        price: 0,
        isPaid: false,
        duration: "4 weeks",
        level: "Beginner",
        rating: 4.4,
        reviewsCount: 1100,
        studentsCount: 14000,
        published: true
    },
    {
        title: "Public Speaking & Communication",
        description: "Overcome stage fright and communicate with high impact.",
        shortDescription: "Speak with confidence and clarity.",
        imageUrl: "https://images.unsplash.com/photo-1544531585-9847b68c8c86?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1544531585-9847b68c8c86?auto=format&fit=crop&w=200&q=80",
        category: "Personal Development",
        tags: ["Soft Skills", "Communication", "Free"],
        price: 0,
        isPaid: false,
        duration: "2 weeks",
        level: "Beginner",
        rating: 4.9,
        reviewsCount: 2300,
        studentsCount: 32000,
        published: true
    },
    {
        title: "Graphic Design Basics",
        description: "Fundamentals of visual storytelling using modern tools.",
        shortDescription: "Express your creativity visually.",
        imageUrl: "https://images.unsplash.com/photo-1561070791-20a2335f6068?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1561070791-20a2335f6068?auto=format&fit=crop&w=200&q=80",
        category: "Design",
        tags: ["Design", "Creativity", "Free"],
        price: 0,
        isPaid: false,
        duration: "3 weeks",
        level: "Beginner",
        rating: 4.7,
        reviewsCount: 780,
        studentsCount: 11000,
        published: true
    },
    {
        title: "Excel Essentials for Business",
        description: "Learn formulas, pivot tables, and data visualization in Excel.",
        shortDescription: "The must-have tool for office productivity.",
        imageUrl: "https://images.unsplash.com/photo-1543286386-713bdd548da4?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1543286386-713bdd548da4?auto=format&fit=crop&w=200&q=80",
        category: "Business",
        tags: ["Excel", "Productivity", "Free"],
        price: 0,
        isPaid: false,
        duration: "3 weeks",
        level: "Beginner",
        rating: 4.8,
        reviewsCount: 1500,
        studentsCount: 25000,
        published: true
    },
    {
        title: "Photography for Social Media",
        description: "Capture stunning photos using your smartphone or DSLR.",
        shortDescription: "Make your feed look professional.",
        imageUrl: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1542038784456-1ea8e935640e?auto=format&fit=crop&w=200&q=80",
        category: "Design",
        tags: ["Photography", "Insta", "Free"],
        price: 0,
        isPaid: false,
        duration: "2 weeks",
        level: "Beginner",
        rating: 4.7,
        reviewsCount: 620,
        studentsCount: 9400,
        published: true
    },
    {
        title: "Introduction to SQL",
        description: "Learn how to query databases and manage data efficiently.",
        shortDescription: "The language of data management.",
        imageUrl: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?auto=format&fit=crop&w=200&q=80",
        category: "Technology",
        tags: ["SQL", "Database", "Free"],
        price: 0,
        isPaid: false,
        duration: "4 weeks",
        level: "Beginner",
        rating: 4.6,
        reviewsCount: 1100,
        studentsCount: 13000,
        published: true
    },
    {
        title: "Time Management Secrets",
        description: "Boost your productivity with proven time management frameworks.",
        shortDescription: "Do more in less time.",
        imageUrl: "https://images.unsplash.com/photo-1495364141860-b0d0360ad4a3?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1495364141860-b0d0360ad4a3?auto=format&fit=crop&w=200&q=80",
        category: "Personal Development",
        tags: ["Productivity", "Soft Skills", "Free"],
        price: 0,
        isPaid: false,
        duration: "1 week",
        level: "Beginner",
        rating: 4.9,
        reviewsCount: 4200,
        studentsCount: 56000,
        published: true
    },
    {
        title: "Basics of Stock Market",
        description: "Understand how the stock market works and the basics of investing.",
        shortDescription: "Start your financial literacy journey.",
        imageUrl: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=200&q=80",
        category: "Finance",
        tags: ["Finance", "Investing", "Free"],
        price: 0,
        isPaid: false,
        duration: "3 weeks",
        level: "Beginner",
        rating: 4.8,
        reviewsCount: 2800,
        studentsCount: 31000,
        published: true
    },
    {
        title: "Creative Writing Workshop",
        description: "Unleash your inner author and learn storytelling techniques.",
        shortDescription: "Write stories that resonate.",
        imageUrl: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=200&q=80",
        category: "Personal Development",
        tags: ["Writing", "Creativity", "Free"],
        price: 0,
        isPaid: false,
        duration: "4 weeks",
        level: "Beginner",
        rating: 4.7,
        reviewsCount: 950,
        studentsCount: 8200,
        published: true
    },

    // 15 PAID COURSES
    {
        title: "Full Stack Web Development",
        description: "Comprehensive bootcamp covering MERN stack and industrial practices.",
        shortDescription: "Become a professional full-stack developer.",
        imageUrl: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=200&q=80",
        category: "Technology",
        tags: ["MERN", "Node.js", "Fullstack"],
        price: 8999,
        isPaid: true,
        duration: "12 weeks",
        level: "Advanced",
        rating: 4.9,
        reviewsCount: 560,
        studentsCount: 3200,
        published: true
    },
    {
        title: "Advanced Data Science & AI",
        description: "Master complex algorithms with Scikit-learn and TensorFlow.",
        shortDescription: "Predict the future with Data Science.",
        imageUrl: "https://images.unsplash.com/photo-1551288049-bbbda50a5f4a?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1551288049-bbbda50a5f4a?auto=format&fit=crop&w=200&q=80",
        category: "Data Science",
        tags: ["AI", "TensorFlow", "Advanced"],
        price: 9999,
        isPaid: true,
        duration: "14 weeks",
        level: "Advanced",
        rating: 4.8,
        reviewsCount: 420,
        studentsCount: 2100,
        published: true
    },
    {
        title: "Mobile App Development (Flutter)",
        description: "Build cross-platform apps for iOS and Android with a single codebase.",
        shortDescription: "Code once, deploy everywhere.",
        imageUrl: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=200&q=80",
        category: "Technology",
        tags: ["Flutter", "Dart", "Mobile"],
        price: 7999,
        isPaid: true,
        duration: "10 weeks",
        level: "Intermediate",
        rating: 4.7,
        reviewsCount: 380,
        studentsCount: 4500,
        published: true
    },
    {
        title: "DevOps & Cloud Engineering",
        description: "Learn Docker, Kubernetes, and AWS deployment pipelines.",
        shortDescription: "Scale applications like a pro.",
        imageUrl: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?auto=format&fit=crop&w=200&q=80",
        category: "Technology",
        tags: ["AWS", "Docker", "DevOps"],
        price: 8499,
        isPaid: true,
        duration: "10 weeks",
        level: "Advanced",
        rating: 4.9,
        reviewsCount: 290,
        studentsCount: 1800,
        published: true
    },
    {
        title: "Cybersecurity Professional",
        description: "Protect digital assets via ethical hacking and network security.",
        shortDescription: "Secure the digital world.",
        imageUrl: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=200&q=80",
        category: "Technology",
        tags: ["Security", "Hacking", "Paid"],
        price: 9499,
        isPaid: true,
        duration: "12 weeks",
        level: "Advanced",
        rating: 4.8,
        reviewsCount: 650,
        studentsCount: 5200,
        published: true
    },
    {
        title: "AI & Neural Networks Masterclass",
        description: "Deep dive into GANs, Transformers, and LLMs.",
        shortDescription: "The cutting edge of AI.",
        imageUrl: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1677442136019-21780ecad995?auto=format&fit=crop&w=200&q=80",
        category: "Data Science",
        tags: ["LLM", "Neural", "Paid"],
        price: 9999,
        isPaid: true,
        duration: "16 weeks",
        level: "Advanced",
        rating: 5.0,
        reviewsCount: 120,
        studentsCount: 800,
        published: true
    },
    {
        title: "Product Management Certification",
        description: "Learn agile development and market entry strategies.",
        shortDescription: "Lead products to success.",
        imageUrl: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1531403009284-440f080d1e12?auto=format&fit=crop&w=200&q=80",
        category: "Business",
        tags: ["Product", "Strategy", "Paid"],
        price: 6999,
        isPaid: true,
        duration: "8 weeks",
        level: "Intermediate",
        rating: 4.6,
        reviewsCount: 540,
        studentsCount: 6100,
        published: true
    },
    {
        title: "Financial Modeling & Valuation",
        description: "Master Excel for high-end financial business models.",
        shortDescription: "Master the numbers behind business.",
        imageUrl: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=200&q=80",
        category: "Finance",
        tags: ["Finance", "Excel", "Paid"],
        price: 5999,
        isPaid: true,
        duration: "6 weeks",
        level: "Intermediate",
        rating: 4.7,
        reviewsCount: 920,
        studentsCount: 4200,
        published: true
    },
    {
        title: "Blockchain & Web3 Foundations",
        description: "Understand Smart Contracts and Solidity on Ethereum.",
        shortDescription: "The future is decentralized.",
        imageUrl: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&w=200&q=80",
        category: "Technology",
        tags: ["Blockchain", "Web3", "Paid"],
        price: 7499,
        isPaid: true,
        duration: "8 weeks",
        level: "Intermediate",
        rating: 4.8,
        reviewsCount: 150,
        studentsCount: 1200,
        published: true
    },
    {
        title: "Mastering Digital Illustration",
        description: "Pro techniques for character design and environment art.",
        shortDescription: "Draw like a pro designer.",
        imageUrl: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=200&q=80",
        category: "Design",
        tags: ["Art", "Illustration", "Paid"],
        price: 4499,
        isPaid: true,
        duration: "6 weeks",
        level: "Intermediate",
        rating: 4.9,
        reviewsCount: 210,
        studentsCount: 1800,
        published: true
    },
    {
        title: "Professional MBA Essentials",
        description: "Key concepts from top-tier MBA programs condensed.",
        shortDescription: "Fast-track your business career.",
        imageUrl: "https://images.unsplash.com/photo-1522071823991-b580ea7ef3c5?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1522071823991-b580ea7ef3c5?auto=format&fit=crop&w=200&q=80",
        category: "Business",
        tags: ["MBA", "Business", "Paid"],
        price: 8999,
        isPaid: true,
        duration: "10 weeks",
        level: "Advanced",
        rating: 4.7,
        reviewsCount: 340,
        studentsCount: 2900,
        published: true
    },
    {
        title: "Advanced SEO & Growth Hacking",
        description: "Data-driven strategies to dominate search engines.",
        shortDescription: "Scale your traffic exponentially.",
        imageUrl: "https://images.unsplash.com/photo-1562577309-4932fdd64cd1?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1562577309-4932fdd64cd1?auto=format&fit=crop&w=200&q=80",
        category: "Marketing",
        tags: ["SEO", "Growth", "Paid"],
        price: 5499,
        isPaid: true,
        duration: "5 weeks",
        level: "Advanced",
        rating: 4.8,
        reviewsCount: 480,
        studentsCount: 3600,
        published: true
    },
    {
        title: "Data Visualization with Tableau",
        description: "Transform complex data into beautiful interactive dashboards.",
        shortDescription: "Visualize your data insights.",
        imageUrl: "https://images.unsplash.com/photo-1551288049-bbbda50a5f4a?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1551288049-bbbda50a5f4a?auto=format&fit=crop&w=200&q=80",
        category: "Data Science",
        tags: ["Tableau", "DataViz", "Paid"],
        price: 6499,
        isPaid: true,
        duration: "7 weeks",
        level: "Intermediate",
        rating: 4.7,
        reviewsCount: 310,
        studentsCount: 2200,
        published: true
    },
    {
        title: "Leadership & Management Skills",
        description: "Master the art of leading teams in a remote-first world.",
        shortDescription: "Become an inspirational leader.",
        imageUrl: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=200&q=80",
        category: "Personal Development",
        tags: ["Leadership", "Soft Skills", "Paid"],
        price: 7999,
        isPaid: true,
        duration: "8 weeks",
        level: "Advanced",
        rating: 4.9,
        reviewsCount: 890,
        studentsCount: 7500,
        published: true
    },
    {
        title: "Cloud Architecture (Azure/GCP)",
        description: "Design resilient systems on top cloud platforms.",
        shortDescription: "Architect for the cloud era.",
        imageUrl: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=800&q=80",
        thumbnail: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=200&q=80",
        category: "Technology",
        tags: ["Cloud", "Azure", "GCP"],
        price: 9499,
        isPaid: true,
        duration: "10 weeks",
        level: "Advanced",
        rating: 4.8,
        reviewsCount: 230,
        studentsCount: 1500,
        published: true
    }
];

const seedDB = async () => {
    try {
        await mongoose.connect(MONGO_URI);
        console.log("Connected to MongoDB for expanded seeding...");

        await Course.deleteMany({});
        console.log("Cleared existing courses.");

        await Course.insertMany(courses);
        console.log(`Successfully seeded ${courses.length} courses (15 free, 15 paid)!`);

        mongoose.connection.close();
    } catch (err) {
        console.error("Seed error:", err);
        process.exit(1);
    }
};

seedDB();
